POST http://localhost:6969/songs
content-type: application/json

{
    "ids" :["64d2a2af3a54f70b2c2883f3",
    "64ccda0c5fad016c15f71c3d",
    "64ccd9dd5fad016c15f71c39"
    ]
}
###

GET http://localhost:6969/songs/64ccda0c5fad016c15f71c3d

###

POST http://localhost:6969/songs HTTP/1.1
content-type: application/json

{
    "title": "BDIKALAST",
    "artist": "BendaLulu",
    "album": "Bendaron24",
    "year": 2022,
    "genre": ["AniBeshok24", "Alonko"],
    "duration": 1234,
    "album_image": "https://avatars.githubusercontent.com/u/81577071?v=4",
    "preview_url":"https://p.scdn.co/mp3-preview/98123a7d31111d0d9a61c21d4ce6e9215a8f5903?cid=38e67659f07443c3be7ebf8f88362892"
}

###

DELETE http://localhost:1234/songs/Plain_JaneA$AP_FergStill_Striving2017

###

PATCH http://localhost:6969/songs/MekleronBurgeronBendaron2023 HTTP/1.1
content-type: application/json

{
    "title": "Mekleron1",
    "artist": "Burgeron1",
    "album": "Bendaron1",
    "year": 2024,
    "genre": ["AniBeshok1", "Rap1"],
    "duration": 12345,
    "album_image": "https://avatars.githubusercontent.com/u/81577071?v=4",
    "preview_url":"https://p.scdn.co/mp3-preview/34934b16056fc0f696dfccfd48ec62b1202d5b18?cid=38e67659f07443c3be7ebf8f88362892"
}

###

curl -X POST "https://accounts.spotify.com/api/token" \
     -H "Content-Type: application/x-www-form-urlencoded" \
     -d "grant_type=client_credentials&client_id=38e67659f07443c3be7ebf8f88362892&client_secret=627725320547433196284da785fcb187"

###


curl "https://api.spotify.com/v1/artists/4Z8W4fKeB5YxbusRsdQVPb" \
     -H "Authorization: Bearer  BQAsKeUYf-tPbmT0GXi1VV83-N4R_QFzVi2IIE7TZNPlqTIQrLAkLPJNVN5n58Cl-wR7Dz4oggmtdPZuw_727bHWF3Kw-Qc2Z60-C3vq2pt_-vnOpBk"


###

curl --request GET \
  --url https://api.spotify.com/v1/albums/4aawyAB9vmqN3uQ7FjRGTy \
  --header 'Authorization: Bearer BQCuWq...noUVSg'
